#!/bin/bash

num_monitors="$(xrandr --query | grep ' connected' | wc -l)"

if [ $num_monitors -eq 1 ]; then
  /usr/bin/nitrogen --head=0 --set-zoom-fill $1
else
  /usr/bin/nitrogen --head=0 --set-zoom-fill $1
  /usr/bin/nitrogen --head=1 --set-zoom-fill $1
fi
