#!/usr/bin/env sh
#
# Credit to gurkensalat
# https://faq.i3wm.org/question/6421/conditional-monitor-cofiguration.1.html
#

onConnection() {
    echo onConnection
    xrandr --output eDP1 --auto
    xrandr --output DP2 --primary --mode 3440x1440 --left-of eDP1
    bspc wm -r
    #xrandr --output DP2 --auto
    #xrandr --output eDP1 --off
    #pacmd set-card-profile 0 "output:hdmi-stereo+input:analog-stereo"
    #feh --bg-fill ~/.i3/res/wallpaper.png
}
onDisconnection() {
    echo onDisconnection
    xrandr --output eDP1 --auto
    xrandr --output DP2 --off
    bspc wm -r
    #pacmd set-card-profile 0 "output:analog-stereo+input:analog-stereo"
    #feh --bg-fill ~/.i3/res/wallpaper.png
}

#########################

statefile="`mktemp`"

quit() {
    rm "$statefile"
    exit 1
}
trap quit SIGINT SIGTERM

getstate() {
    state="`xrandr -q | wc -l`"
}
savestate() {
    echo "$state" > "$statefile"
}
getstate
savestate

xev -root -event randr | grep --line-buffered XRROutputChangeNotifyEvent | \
while IFS= read -r line; do
    getstate
    old="`cat "$statefile"`"
    if [ "$state" -gt "$old" ]; then
        onConnection
    elif [ "$state" -lt "$old" ]; then
        onDisconnection
    fi
    savestate
done
