#!/bin/env bash

rcolor=$(xrdb -query | grep '.color1:' | awk '{print $NF}' | cut -c2-)

while :; do
    wid="$(bspc subscribe -c 1 node_focus | cut -d' ' -f4)"
    owner_of_window="$(ps -o user= "$(xdo pid "$wid")")"
    [[ "$USER" != "$owner_of_window" ]] && case "$owner_of_window" in
        #ejvend)  chwb -c 0x110a49 -s "$(bspc config focused_border_color)" "$wid" ;;
        root) chwb -c $rcolor -s "$(bspc config focused_border_color)" "$wid" ;;
        #root) chwb -c 0x995555 -s "$(bspc config focused_border_color)" "$wid" ;;
        #*)    chwb -c 0xaa4700 -s "$(bspc config focused_border_color)" "$wid" ;;
    esac
done
