#!/usr/bin/env bash

# nodes=( $(bspc query -N -n .hidden ) ) && s=$(xtitle ${nodes[@]} | 
#         rofi -dmenu -i -format i -p "Hidden windows: ")
#
# c=n
#
# if [[ -n "$s" ]]; then
#     bspc query -N -n >/dev/null || c=d
#     bspc node "${nodes[$s]}" -${c} focused -g hidden=off -f
# fi

selection=`for id in $(bspc query -N -n .hidden); do
                title=$(~/.local/bin/xtitle $id)
                #notify-send "${id} ${title}"
                [[ -z "$title" ]] && title="<unnamed>"
                echo $id - $title
            done | rofi -window-thumbnail -dmenu -i -p "Hidden windows" | cut -f1 -d' '`
            
[[ -z "$selection" ]] && exit 1

#notify-send "${selection}"
bspc node ${selection} -g hidden=off


